<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <link rel="shortcut icon" href="../images/image3.png" type="image/x-icon">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>JS LAIR</title>
  <link rel="stylesheet" href="../styles/fonts.css">
  <link rel="stylesheet" href="../styles/style-pages.css">
  <link rel="stylesheet" href="../styles/prism.css">
  <script src="../scripts/prism.js" defer></script>
  <script src="../scripts/script.js" defer></script>
</head>
<body>
  
  <header class="header">
    <ul>
      <li><a href="../index.html">Дом</a></li>
      <li><a href="../pages/browse.html">Просмотр</a></li>
      <li><a href="../pages/other.html">Прочее</a></li>
      <li><a href="#">Проект</a></li>
    </ul>
  </header>

  <article>
    <h1>Промисы</h1>
    <hr>
    <p>Синтаксис создания <code>Promise</code>:</p>
<pre>
  <code class="lang-js">
    let promise = new Promise(function(resolve, reject) {
      // функция-исполнитель (executor)
    });
  </code>
</pre>
    <p>Функция, переданная в конструкцию <code>new Promise</code>, называется исполнитель (executor). Когда <code>Promise</code> создаётся, она запускается автоматически. Она должна содержать «создающий» код, который когда-нибудь создаст результат.</p>
    <p>Её аргументы <code>resolve</code> и <code>reject</code> – это колбэки, которые предоставляет сам JavaScript. Наш код – только внутри исполнителя.</p>
    <p>Когда он получает результат, сейчас или позже – не важно, он должен вызвать один из этих колбэков:</p>
    <ul>
      <li><code>resolve(value)</code> — если работа завершилась успешно, с результатом <code>value</code>.</li>
      <li><code>reject(error)</code> — если произошла ошибка, <code>error</code> – объект ошибки.</li>
    </ul>
    <p>Итак, исполнитель запускается автоматически, он должен выполнить работу, а затем вызвать <code>resolve</code> или <code>reject</code>.</p>
    <p>У объекта <code>promise</code>, возвращаемого конструктором <code>new Promise</code>, есть внутренние свойства:</p>
    <ul>
      <li><code>state</code> («состояние») — вначале <code>"pending"</code> («ожидание»), потом меняется на <code>"fulfilled"</code> («выполнено успешно») при вызове <code>resolve</code> или на <code>"rejected"</code> («выполнено с ошибкой») при вызове <code>reject</code>.</li>
      <li><code>result</code> («результат») — вначале <code>undefined</code>, далее изменяется на <code>value</code> при вызове <code>resolve(value)</code> или на <code>error</code> при вызове <code>reject(error)</code>.</li>
    </ul>
    <p>Так что исполнитель по итогу переводит <code>promise</code> в одно из двух состояний:</p>
    <ul><img src="../images/23.JPG" alt="1"></ul>
    <p>Ниже пример конструктора <code>Promise</code> и простого исполнителя с кодом, дающим результат с задержкой (через <code>setTimeout</code>):</p>
<pre>
  <code class="lang-js">
    let promise = new Promise(function(resolve, reject) {
      // эта функция выполнится автоматически, при вызове new Promise

      // через 1 секунду сигнализировать, что задача выполнена с результатом "done"
      setTimeout(() => resolve("done"), 1000);
    });
  </code>
</pre>
    <p>Мы можем наблюдать две вещи, запустив код выше:</p>
    <ol>
      <li>Функция-исполнитель запускается сразу же при вызове <code>new Promise</code>.</li>
      <li>Исполнитель получает два аргумента: <code>resolve</code> и <code>reject</code> — это функции, встроенные в JavaScript, поэтому нам не нужно их писать. Нам нужно лишь позаботиться, чтобы исполнитель вызвал одну из них по готовности.</li>
    </ol>
    <p>Спустя одну секунду «обработки» исполнитель вызовет <code>resolve("done")</code>, чтобы передать результат:</p>
    <ul><img src="../images/24.JPG" alt="1"></ul>
    <p>Это был пример успешно выполненной задачи, в результате мы получили «успешно выполненный» промис.</p>
    <p>А теперь пример, в котором исполнитель сообщит, что задача выполнена с ошибкой:</p>
<pre>
  <code class="lang-js">
    let promise = new Promise(function(resolve, reject) {
      // спустя одну секунду будет сообщено, что задача выполнена с ошибкой
      setTimeout(() => reject(new Error("Whoops!")), 1000);
    });
  </code>
</pre>
    <ul><img src="../images/25.JPG" alt="1"></ul>
    <p>Подведём промежуточные итоги: исполнитель выполняет задачу (что-то, что обычно требует времени), затем вызывает <code>resolve</code> или <code>reject</code>, чтобы изменить состояние соответствующего <code>Promise</code>.</p>
    <p>Промис – и успешный, и отклонённый будем называть «завершённым», в отличие от изначального промиса «в ожидании».</p>

    <hr>
    <h3>Может быть что-то одно: либо результат, либо ошибка</h3>
    <p>Исполнитель должен вызвать что-то одно: <code>resolve</code> или <code>reject</code>. Состояние промиса может быть изменено только один раз.</p>
    <p>Все последующие вызовы <code>resolve</code> и <code>reject</code> будут проигнорированы:</p>
<pre>
  <code class="lang-js">
    let promise = new Promise(function(resolve, reject) {
      resolve("done");

      reject(new Error("…")); // игнорируется
      setTimeout(() => resolve("…")); // игнорируется
    });
  </code>
</pre>
    <p>Идея в том, что задача, выполняемая исполнителем, может иметь только один итог: результат или ошибку.</p>
    <p>акже заметим, что функция <code>resolve/reject</code> ожидает только один аргумент (или ни одного). Все дополнительные аргументы будут проигнорированы.</p>
    <hr>
    <h3>Вызывайте <code>reject</code> с объектом <code>Error</code></h3>
    <p>В случае, если что-то пошло не так, мы должны вызвать <code>reject</code>. Это можно сделать с аргументом любого типа (как и <code>resolve</code>), но рекомендуется использовать объект <code>Error</code> (или унаследованный от него).</p>
    <hr>
    <h3>Вызов <code>resolve/reject</code> сразу</h3>
    <p>Обычно исполнитель делает что-то асинхронное и после этого вызывает <code>resolve/reject</code>, то есть через какое-то время. Но это не обязательно, <code>resolve</code> или <code>reject</code> могут быть вызваны сразу:</p>
<pre>
  <code class="lang-js">
    let promise = new Promise(function(resolve, reject) {
      // задача, не требующая времени
      resolve(123); // мгновенно выдаст результат: 123
    });
  </code>
</pre>
    <p>Это может случиться, например, когда мы начали выполнять какую-то задачу, но тут же увидели, что ранее её уже выполняли, и результат закеширован.</p>
    <p>Такая ситуация нормальна. Мы сразу получим успешно завершённый <code>Promise</code>.</p>
    <hr>
    <h3>Свойства <code>state</code> и <code>result</code> – внутренние</h3>
    <p>Свойства <code>state</code> и <code>result</code> – это внутренние свойства объекта <code>Promise</code> и мы не имеем к ним прямого доступа. Для обработки результата следует использовать методы <code>.then/.catch/.finally</code>, про них речь пойдёт дальше.</p>
    <hr>

    <h2>Потребители: then, catch</h2>
    <p>Объект <code>Promise</code> служит связующим звеном между исполнителем («создающим» кодом) и функциями-потребителями, которые получат либо результат, либо ошибку. Функции-потребители могут быть зарегистрированы (подписаны) с помощью методов <code>.then</code> и <code>.catch</code>.</p>
    <h3>then</h3>
    <p>Наиболее важный и фундаментальный метод – <code>.then</code></p>
    <p>Синтаксис:</p>
<pre>
  <code class="lang-js">
    promise.then(
      function(result) { /* обработает успешное выполнение */ },
      function(error) { /* обработает ошибку */ }
    );
  </code>
</pre>
    <p>Первый аргумент метода <code>.then</code> – функция, которая выполняется, когда промис переходит в состояние «выполнен успешно», и получает результат.</p>
    <p>Второй аргумент <code>.then</code> – функция, которая выполняется, когда промис переходит в состояние «выполнен с ошибкой», и получает ошибку.</p>
    <p>Например, вот реакция на успешно выполненный промис:</p>
<pre>
  <code class="lang-js">
    let promise = new Promise(function(resolve, reject) {
      setTimeout(() => resolve("done!"), 1000);
    });

    // resolve запустит первую функцию, переданную в .then
    promise.then(
      result => alert(result), // выведет "done!" через одну секунду
      error => alert(error) // не будет запущена
    );
  </code>
</pre>
    <p>Выполнилась первая функция.</p>
    <p>А в случае ошибки в промисе – выполнится вторая:</p>
<pre>
  <code class="lang-js">
    let promise = new Promise(function(resolve, reject) {
      setTimeout(() => reject(new Error("Whoops!")), 1000);
    });

    // reject запустит вторую функцию, переданную в .then
    promise.then(
      result => alert(result), // не будет запущена
      error => alert(error) // выведет "Error: Whoops!" спустя одну секунду
    );
  </code>
</pre>
    <p>Если мы заинтересованы только в результате успешного выполнения задачи, то в <code>then</code> можно передать только одну функцию:</p>
<pre>
  <code class="lang-js">
    let promise = new Promise(resolve => {
      setTimeout(() => resolve("done!"), 1000);
    });

    promise.then(alert); // выведет "done!" спустя одну секунду
  </code>
</pre>
    <h3>catch</h3>
    <p>Если мы хотели бы только обработать ошибку, то можно использовать null в качестве первого аргумента: <code>.then(null, errorHandlingFunction)</code>. Или можно воспользоваться методом <code>.catch(errorHandlingFunction)</code>, который сделает то же самое:</p>
<pre>
  <code class="lang-js">
    let promise = new Promise((resolve, reject) => {
      setTimeout(() => reject(new Error("Ошибка!")), 1000);
    });

    // .catch(f) это то же самое, что promise.then(null, f)
    promise.catch(alert); // выведет "Error: Ошибка!" спустя одну секунду
  </code>
</pre>
    <p>Вызов <code>.catch(f)</code> – это сокращённый, «укороченный» вариант <code>.then(null, f)</code>.</p>

    <h2>Очистка: finally</h2>
    <p>Метод <code>.finally()</code> добавляется в конец цепочки промисов и принимает функцию, которая будет выполнена после того, как промис будет разрешен или отклонен. Важно отметить, что функция, вызываемая через <code>.finally()</code>, не получает никаких аргументов, то есть в ней недоступен результат или ошибка из промиса.</p>
    <p>Пример:</p>
<pre>
  <code class="lang-js">
    / Функция для имитации загрузки данных
    function fetchData() {
      return new Promise((resolve, reject) => {
        // Имитация асинхронной операции с использованием setTimeout
        setTimeout(() => {
          // Имитируем успешную или неуспешную загрузку с вероятностью 50%
          if (Math.random() > 0.5) {
            resolve("Данные загружены успешно");
          } else {
            reject("Ошибка загрузки данных");
          }
        }, 2000); // Задержка в 2 секунды
      });
    }

    // Использование промиса с .finally()
    fetchData()
      .then(data => {
        console.log("Результат:", data); // Обработка успешного результата
      })
      .catch(error => {
        console.error("Ошибка:", error); // Обработка ошибки
      })
      .finally(() => {
        console.log("Загрузка завершена."); // Выполняется всегда после .then или .catch
      });
  </code>
</pre>
    <p>Метод <code>.finally()</code> особенно полезен в следующих случаях:</p>
    <ol>
      <li>Очистка ресурсов: например, закрытие файловых дескрипторов или сетевых соединений, независимо от результата операции.</li>
      <li>Скрытие индикаторов загрузки или сообщений о процессе: если вы показываете пользователю индикатор загрузки, его нужно скрыть после завершения операции, независимо от исхода.</li>
      <li>Логирование: запись информации о завершении операции в логи, не вдаваясь в детали результата.</li>
    </ol>
    <p>Использование <code>.finally()</code> в JavaScript позволяет упростить управление асинхронными операциями, делая код чище и более надежным. Этот метод помогает обеспечить, что необходимые действия по завершении работы промиса будут выполнены, независимо от того, с успехом он завершился или с ошибкой.</p>







  </article>
  <button id="scrollToTopButton">&#8593;</button>
</body>
</html>